<script>
export let component;
export let sections;
export let style;

import { getContext } from 'svelte';
import { fade } from 'svelte/transition';

import utils from '$utils/general.js';

import CssProperties from '$components/css-properties.svelte';
import CssVariables from '$components/css-variables.svelte';
import Highlighter from '$components/highlighter.svelte';
import Modal from '$components/modal.svelte';

const { selectedThemeObject, userThemeObject } = getContext('theme');

let mode = 'variables';
let helpOpen = false;

$: style = makeStyle($userThemeObject);
$: code = makeCode(style);

const transitions = {
	in: {
		duration: 200,
		delay: 200
	},
	out: {
		duration: 200
	}
};

function setMode(m) {
	return () => {
		mode = m;
	};
}

function makeStyle() {
	const obj = utils.clone($userThemeObject[component]);
	obj.variables = utils.diff(
		obj.variables,
		$selectedThemeObject[component]?.variables
	);
	return utils.clean(obj);
}

function makeCode() {
	return `//style.js\nexport default style = ${JSON.stringify(style)};`;
}
</script>

<div class="grid grid-rows-[auto_1fr] gap-4 lg:grid-cols-2 lg:grid-rows-1">
	<div>
		<div class="mb-4 flex cursor-default gap-3 text-xl">
			<div
				class:active={mode === 'variables'}
				on:click={setMode('variables')}
				on:keyup={setMode('variables')}>
				Variables
			</div>
			<div
				class:active={mode === 'properties'}
				on:click={setMode('properties')}
				on:keyup={setMode('properties')}>
				Properties
			</div>
		</div>
		<div class="grid">
			{#if mode === 'variables'}
				<div class="cell-1" in:fade={transitions.in} out:fade={transitions.out}>
					<CssVariables {component} />
				</div>
			{:else if mode === 'properties'}
				<div class="cell-1" in:fade={transitions.in} out:fade={transitions.out}>
					<CssProperties {component} {sections} />
				</div>
			{/if}
		</div>
	</div>
	<div class="row-start-1 lg:row-auto">
		<div
			class="my-2 cursor-pointer text-blue-500 hover:underline"
			on:click={() => (helpOpen = true)}
			on:keyup={() => (helpOpen = true)}>
			How do I use this?
		</div>
		<div class="self-start overflow-hidden rounded">
			<Highlighter language="js" strict={true} {code} />
		</div>
	</div>
</div>
<Modal slim={true} bind:open={helpOpen}>
	<svelte:fragment slot="title">Custom styling</svelte:fragment>
	<a class="mb-2 block text-[0.95rem]" href="/styling">
		Learn more about how Colibri's styling system works
	</a>
	<div>
		To integrate custom styling into your components, you have two options:
	</div>
	<ol class="my-1 ml-4 list-inside list-decimal">
		<li>Apply styling globally as a theme</li>
		<li>Apply styling only to specific instances of the component</li>
	</ol>
	<div class="underline">Global</div>
	<div>
		Any values you change will be stored in a theme object. You can find
		instructions on how to download and use your custom theme in the
		<a href="/theme-editor">theme editor</a>.
		<div class="my-1" />
		Don't worry about losing the values you've entered, they are preserved as you
		navigate.
	</div>
	<div class="mt-1 underline">Specific</div>
	<div>
		The example code shows how to apply the styles selectively to specific
		instances of a component. You can copy the style object generated by this
		section, and pass it as a prop to the component.
	</div>
</Modal>

<style>
.active {
	@apply border-b-[3px] border-b-blue-500;
}
</style>
