<script>
export let component;
export let sections;

import { getContext } from 'svelte';
import { fade } from 'svelte/transition';

import utils from '$utils/general.js';

import CssProperties from '$components/css-properties.svelte';
import CssVariables from '$components/css-variables.svelte';
import Highlighter from '$components/highlighter.svelte';
import Modal from '$components/modal.svelte';

let mode = 'properties';
let helpOpen = false;

let properties = {};
let variables;

const style = getContext('style');

$: $style = makeStyle(properties, variables);
$: code = makeCode($style);

const transitions = {
	in: {
		duration: 200,
		delay: 200
	},
	out: {
		duration: 200
	}
};

function setMode(m) {
	return () => {
		mode = m;
	};
}

function makeStyle() {
	return utils.clean({
		...properties,
		variables
	});
}

function makeCode() {
	return `//style.js\n` + `export default style = ${JSON.stringify($style)};`;
}
</script>

<div class="grid grid-cols-2 gap-4">
	<div>
		<div class="mb-4 flex cursor-default gap-3 text-xl">
			<div
				class:active={mode === 'properties'}
				on:click={setMode('properties')}>
				Properties
			</div>
			<div class:active={mode === 'variables'} on:click={setMode('variables')}>
				Variables
			</div>
		</div>
		<div class="grid">
			{#if mode === 'properties'}
				<div class="cell-1" in:fade={transitions.in} out:fade={transitions.out}>
					<CssProperties {sections} bind:properties />
				</div>
			{:else if mode === 'variables'}
				<div class="cell-1" in:fade={transitions.in} out:fade={transitions.out}>
					<CssVariables {component} bind:variables />
				</div>
			{/if}
		</div>
	</div>
	<div>
		<div
			class="my-2 cursor-pointer text-blue-500 hover:underline"
			on:click={() => (helpOpen = true)}>
			How do I use this?
		</div>
		<div class="self-start overflow-hidden rounded">
			<Highlighter language="js" strict={true} {code} />
		</div>
	</div>
</div>
<Modal slim={true} bind:open={helpOpen}>
	<svelte:fragment slot="title">Custom styling</svelte:fragment>
	<div class="mb-1 text-[0.95rem]">
		<a href="/styling">Learn about how Colibri's styling system works</a>
	</div>
	<div>
		To integrate custom styling into your components, you have two options:
	</div>
	<ol class="my-1 ml-4 list-inside list-decimal">
		<li>Apply the styling globally to all instances of the component</li>
		<li>Apply the styling only to specific instances of the component</li>
	</ol>
	<div class="underline">Global</div>
	<div>
		To apply the styles globally, you can go to the
		<a href="/theme-editor">theme editor</a>
		to download your theme file, and you will find instructions there on how to add
		it to your project. Don't worry about losing the values you've entered, they
		are preserved as you navigate.
		<div class="my-1" />
		It is important to note that the theme files will only apply styling from the
		variables. Classes and inline styles can only be applied to specific instances.
	</div>
	<div class="mt-1 underline">Specific</div>
	<div>
		The example code shows how to apply the styles selectively to specific
		instances of a component. You can copy the style object generated by this
		section, and pass it as a prop to the component.
	</div>
</Modal>

<style>
.active {
	@apply border-b-[3px] border-b-blue-500;
}
</style>
